name = "tp1"
uuid = "19cbed2b-2ce3-4df5-be46-cb6ace1f3f3a"
authors = ["malustewart <mastewart@itba.edu.ar>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
ArgParse = "1.2.0"
JSON = "0.21.4"
Plots = "1.40.17"
